# Generated by Django 4.0 on 2021-12-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('shortened_link', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('link', models.URLField(max_length=150)),
            ],
        ),
    ]
